image: 
  repository: villaja/villaja-app
  tag: e6b5631
  pullPolicy: IfNotPresent
services:
  database:
    type: ClusterIP
    port: 8000
ingress:
  enabled: false
service_account:
  enabled: false
autoscaling:
  enabled: false

